import type { Metadata } from "next";
import '@/app/ui/globals.css';
import { inter } from '@/app/ui/fonts';
import NavLinks from '@/app/ui/nav-links';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-white`}>
        <NavLinks/>
        {children}
      </body>
    </html>
  );
}
